sonar.projectKey=cntm-labs_nucleus
sonar.projectName=nucleus
sonar.sources=.
sonar.host.url=http://sonarqube.devops.svc.cluster.local:9000
# ยกเว้นไฟล์ Java เพื่อให้ภาษาอื่นๆ สแกนผ่านได้โดยไม่ต้องรอการ Build
sonar.exclusions=**/*.java, **/node_modules/**, **/dist/**, **/build/**, **/.git/**
