apiVersion: v1
kind: Service
metadata:
  name: nucleus-server
  namespace: nucleus
  labels:
    app.kubernetes.io/name: nucleus
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nucleus
    app.kubernetes.io/component: server
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
